apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.nameOverride }}
spec:
  selector:
    matchLabels:
      run: {{ .Values.nameOverride }}
  replicas: 1
  template:
    metadata:
      labels:
        run: {{ .Values.nameOverride }}
    spec:
      containers:
      - name: {{ .Values.nameOverride }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: {{ .Values.service.targetPort }}
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m